annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: upgrade ghcr.io/shizunge/endlessh-go to 2025.0914.0
apiVersion: v2
# renovate: image=ghcr.io/shizunge/endlessh-go
appVersion: "2025.0914.0"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.2
description: endlessh-go helm chart
home: https://github.com/zekker6/helm-charts/tree/main/charts/apps/changedetection-io
keywords:
  - ssh
  - honeypot
  - endlessh
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: "zekker6"
    email: "me@zekker.dev"
    url: "https://github.com/zekker6/"
name: endlessh-go
sources:
  - https://github.com/shizunge/endlessh-go
  - https://github.com/zekker6/helm-charts/tree/main/charts/apps/endlessh-go
version: 0.2.0
