annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update erikvl87/languagetool Docker tag to v6.7
apiVersion: v2
# renovate: image=erikvl87/languagetool
appVersion: "6.7-dockerupdate-1"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.2
description: language-tool helm package
home: https://github.com/zekker6/helm-charts/tree/main/charts/apps/language-tool
icon: https://languagetool.org/images/logo_color_with_background.svg?8dae54218b449e94603195c91016bc93
keywords:
  - language-tool
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: zekker6
    email: me@zekker.dev
    url: "https://github.com/zekker6/"
name: language-tool
sources:
  - https://github.com/language-tool/language-tool-docker
version: 1.12.0
