annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: properly pin sha
    - kind: fixed
      description: properly mount persistence volume for sqlite cache
apiVersion: v2
# renovate: image=ghcr.io/theduffman85/crowdsec-web-ui
appVersion: "dev@sha256:b5785723e99764c45415571c444fe3b9c2d749dcbcf091203317a583cffbd35f"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.2
description: crowdsec-web-ui helm package
home: https://github.com/zekker6/helm-charts/tree/main/charts/apps/crowdsec-web-ui
keywords:
  - crowdsec
  - security
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: "zekker6"
    email: "me@zekker.dev"
    url: "https://github.com/zekker6/"
name: crowdsec-web-ui
sources:
  - https://github.com/TheDuffman85/crowdsec-web-ui
  - https://github.com/zekker6/helm-charts/tree/main/charts/apps/crowdsec-web-ui
version: 0.0.3
