annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: update https://github.com/zekker6/helm-charts/tree/main/charts/library/common to 0.5.0
apiVersion: v2
appVersion: "2.7"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.0
description: healthchecks helm package
home: https://github.com/zekker6/helm-charts/tree/master/charts/apps/healthchecks
icon: https://healthchecks.io/static/img/favicon.png
keywords:
  - healthchecks
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: zekker6
    email: zekker6@gmail.com
    url: "https://github.com/zekker6/"
name: healthchecks
sources:
  - https://github.com/linuxserver/docker-healthchecks
  - https://github.com/healthchecks/healthchecks
version: 0.2.0
