annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update docuseal/docuseal Docker tag to v2.3.2
apiVersion: v2
# renovate: image=docuseal/docuseal
appVersion: "2.3.2"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.2
description: docuseal helm package
home: https://github.com/zekker6/helm-charts/tree/main/charts/apps/docuseal
icon: https://www.docuseal.co/favicon-32x32.png
keywords:
  - pdf-signature
  - pdf-sign
  - document-signing
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: "zekker6"
    email: "me@zekker.dev"
    url: "https://github.com/zekker6/"
name: docuseal
sources:
  - https://github.com/docusealco/docuseal
  - https://github.com/zekker6/helm-charts/tree/main/charts/apps/docuseal
version: 1.100.0
