---
apiVersion: v2
appVersion: "0.40.0"
description: changedetection-io helm package
name: changedetection-io
version: 1.8.0
kubeVersion: ">=1.16.0-0"
keywords:
  - changedetection.io
  - urlmonitor
  - website-monitoring
home: https://github.com/zekker6/charts/tree/master/charts/apps/changedetection-io
icon:
sources:
  - https://github.com/dgtlmoon/changedetection.io
  - https://github.com/zekker6/charts/tree/master/charts/apps/changedetection-io
maintainers:
  - name: "zekker6"
    email: "zekker6@gmail.com"
    url: "https://github.com/zekker6/"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: switch to zekker6/common library chart
