annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update matrixdotorg/synapse docker tag to v1.105.0
apiVersion: v2
appVersion: v1.105.0
dependencies:
  - name: postgresql
    version: "15.x"
    repository: "https://charts.bitnami.com/bitnami"
description: A Helm chart to deploy a Matrix homeserver stack into Kubernetes
home: "https://github.com/zekker6/helm-charts/tree/main/charts/apps/matrix"
icon: https://upload.wikimedia.org/wikipedia/commons/7/7c/Matrix_icon.svg
maintainers:
  - name: "zekker6"
    email: "zekker6@gmail.com"
    url: "https://github.com/zekker6/"
name: matrix
sources:
  - "https://github.com/zekker6/helm-charts/tree/main/charts/apps/matrix"
type: application
version: 2.49.0
