annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update matrixdotorg/synapse Docker tag to v1.145.0
apiVersion: v2
# renovate: image=matrixdotorg/synapse
appVersion: v1.145.0
dependencies: []
description: A Helm chart to deploy a Matrix homeserver stack into Kubernetes
home: "https://github.com/zekker6/helm-charts/tree/main/charts/apps/matrix"
icon: https://upload.wikimedia.org/wikipedia/commons/7/7c/Matrix_icon.svg
maintainers:
  - name: "zekker6"
    email: "me@zekker.dev"
    url: "https://github.com/zekker6/"
name: matrix
sources:
  - "https://github.com/zekker6/helm-charts/tree/main/charts/apps/matrix"
type: application
version: 3.12.0
