annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update nocodb/nocodb Docker tag to v0.265.1
apiVersion: v2
# renovate: image=nocodb/nocodb
appVersion: 0.301.0
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.2
description: nocodb - Open Source Airtable Alternative
home: "https://github.com/zekker6/helm-charts/tree/main/charts/apps/nocodb"
icon: https://github.com/nocodb/nocodb/blob/develop/packages/nc-gui/assets/img/icons/64x64.png?raw=true
keywords:
  - nocodb
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: "zekker6"
    email: "me@zekker.dev"
    url: "https://github.com/zekker6/"
name: nocodb
sources:
  - "https://github.com/zekker6/helm-charts/tree/main/charts/apps/nocodb"
version: 1.4.0
