annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update nocodb/nocodb docker tag to v0.111.0
apiVersion: v2
appVersion: v0.111.0
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.4.3
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
description: nocodb - Open Source Airtable Alternative
home: "https://github.com/zekker6/helm-charts/tree/main/charts/apps/nocodb"
icon: https://www.nocodb.com/brand/logo.png
keywords:
  - nocodb
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: "zekker6"
    email: "zekker6@gmail.com"
    url: "https://github.com/zekker6/"
name: nocodb
sources:
  - "https://github.com/zekker6/helm-charts/tree/main/charts/apps/nocodb"
version: 0.21.0
