annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: initial chart release
apiVersion: v2
appVersion: 0.100.2
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.4.0
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
description: nocodb - Open Source Airtable Alternative
home: "https://github.com/zekker6/helm-charts/tree/main/charts/apps/nocodb"
sources:
  - "https://github.com/zekker6/helm-charts/tree/main/charts/apps/nocodb"
icon: https://avatars.githubusercontent.com/u/47271576?s=200&v=4
keywords:
  - nocodb
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: "zekker6"
    email: "zekker6@gmail.com"
    url: "https://github.com/zekker6/"
name: nocodb
version: 0.1.0
