annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update neosmemo/memos docker tag to v0.16.0
apiVersion: v2
appVersion: v0.16.0
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.4.3
description: memos - An open-source, self-hosted memo hub with knowledge management and social networking.
home: "https://github.com/zekker6/helm-charts/tree/main/charts/apps/memos"
icon: https://usememos.com/logo.webp
keywords:
  - memos
  - notes
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: "zekker6"
    email: "zekker6@gmail.com"
    url: "https://github.com/zekker6/"
name: memos
sources:
  - "https://github.com/zekker6/helm-charts/tree/main/charts/apps/memos"
  - "https://github.com/usememos/memos"
version: 0.19.0
