annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update neosmemo/memos docker tag to v0.22.3
apiVersion: v2
appVersion: v0.22.3
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.1
description: memos - An open-source, self-hosted memo hub with knowledge management and social networking.
home: "https://github.com/zekker6/helm-charts/tree/main/charts/apps/memos"
icon: https://www.usememos.com/full-logo-landscape.png
keywords:
  - memos
  - notes
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: "zekker6"
    email: "zekker6@gmail.com"
    url: "https://github.com/zekker6/"
name: memos
sources:
  - "https://github.com/zekker6/helm-charts/tree/main/charts/apps/memos"
  - "https://github.com/usememos/memos"
version: 0.34.0
